---

- name: Install PostgreSQL
  apt:
    name: [postgresql, python-psycopg2]
    update_cache: yes

- name: Start PostgreSQL database
  systemd:
    name: postgresql
    enabled: true
    state: restarted

- name: Create database
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{ postgre_database }}"
    encoding: UTF-8

- name: Create user to access database
  become: true
  become_user: postgres
  postgresql_user:
    db: traces
    name: "{{ postgre_username }}"
    password: "{{ postgre_password }}"